steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'NEXT_PUBLIC_GEMINI_API_KEY=${_NEXT_PUBLIC_GEMINI_API_KEY}',
    '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-lib/elentro',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-lib/elentro']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'elentro'
  - '--image'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-lib/elentro'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'

images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-lib/elentro'

substitutions:
  _NEXT_PUBLIC_GEMINI_API_KEY: ''
  _GEMINI_API_KEY: ''
