steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'NEXT_PUBLIC_GEMINI_API_KEY=${_NEXT_PUBLIC_GEMINI_API_KEY}',
    '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-lib/electron',
    '.'
  ]
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-lib/electron'
substitutions:
  _NEXT_PUBLIC_GEMINI_API_KEY: 'AIzaSyC8U-PbvF8rkpX25eO6ojs6MZbOJ89AnUY'
