import { create } from 'zustand';

/**
 * Represents the structured outcome of an election simulation.
 */
export interface SimulationResult {
  /** High-level summary and contextual backdrop of the simulation. */
  scenario: { summary: string; context: string };
  /** Qualitative feedback from key demographic segments. */
  publicReaction: { urban: string; rural: string; youth: string; media: string };
  /** Quantifiable results including winners, vote share, and turnout. */
  result: { winner: string; voteShare: Record<string, number>; turnout: number; swingFactor: string };
  /** Strategic assessment of what components succeeded or failed. */
  impact: { worked: string[]; failed: string[]; missed: string[] };
  /** Direct insights generated by the Gemini 1.5 Pro AI engine. */
  aiInsight: string;
  /** Alternative scenario analysis provided by the AI. */
  whatIf: string[];
}

/**
 * Zustand store state for managing simulation results and UI status.
 */
interface ResultState {
  /** The current (potentially partial) simulation data. */
  data: Partial<SimulationResult> | null;
  /** Current state of the simulation lifecycle. */
  status: 'idle' | 'loading' | 'success' | 'error';
  /** Error message if simulation fails. */
  error: string | null;
  /** Updates the data state incrementally for streaming UI support. */
  setPartialData: (data: Partial<SimulationResult>) => void;
  /** Updates the lifecycle status. */
  setStatus: (status: 'idle' | 'loading' | 'success' | 'error') => void;
  /** Sets the error state. */
  setError: (error: string | null) => void;
  /** Resets the store to its initial idle state. */
  reset: () => void;
}

export const useResultStore = create<ResultState>((set) => ({
  data: null,
  status: 'idle',
  error: null,
  setPartialData: (data) => set((state) => {
    const newData = { ...state.data, ...data };
    
    if (data.result) newData.result = { ...state.data?.result, ...data.result } as SimulationResult['result'];
    if (data.impact) newData.impact = { ...state.data?.impact, ...data.impact } as SimulationResult['impact'];
    if (data.scenario) newData.scenario = { ...state.data?.scenario, ...data.scenario } as SimulationResult['scenario'];
    if (data.publicReaction) newData.publicReaction = { ...state.data?.publicReaction, ...data.publicReaction } as SimulationResult['publicReaction'];
    
    return { data: newData };
  }),
  setStatus: (status) => set({ status }),
  setError: (error) => set({ error }),
  reset: () => set({ data: null, status: 'idle', error: null }),
}));
